---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    monitoring: prometheus
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-v1
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      version: v1
  template:
    metadata:
      labels:
        app: second-app
        version: v1
        istio: monitor
    spec:
      containers:
        - image: aputra/myapp-lesson155:latest
          imagePullPolicy: Always
          name: second-app
          env:
            - name: SERVICE
              value: second-app
            - name: VERSION
              value: v1
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-v2
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      version: v2
  template:
    metadata:
      labels:
        app: second-app
        version: v2
        istio: monitor
    spec:
      containers:
        - image: aputra/myapp-lesson155:latest
          imagePullPolicy: Always
          name: second-app
          env:
            - name: SERVICE
              value: second-app
            - name: VERSION
              value: v2
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: second-app
  namespace: production
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: second-app
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: second-app
  namespace: production
spec:
  host: second-app
  subsets:
    - name: v1
      labels:
        app: second-app
        version: v1
    - name: v2
      labels:
        app: second-app
        version: v2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: second-app
  namespace: production
spec:
  hosts:
    - istio.example
    - second-app
  gateways:
    - api
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: second-app
            subset: v1
          weight: 10
        - destination:
            host: second-app
            subset: v2
          weight: 90

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-pods
  namespace: production
  labels:
    component: main
spec:
  namespaceSelector:
    matchNames:
    - production
  selector:
    matchLabels:
      istio: monitor
  podMetricsEndpoints:
  - port: http-envoy-prom
    path: stats/prometheus
apiVersion: v1
kind: Service
metadata:
  name: gateway-prom
  namespace: istio-ingress
  labels:
    app: gateway
spec:
  ports:
    - name: metrics
      port: 15090
  selector:
    app: gateway
    istio: gateway
    
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myapp
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - istio-ingress
  selector:
    matchLabels:
      app: gateway
  endpoints:
    - port: metrics
      path: /stats/prometheus
