apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-example
  namespace: dev
spec:
  secretName: cert-example-crt
  dnsNames:
    - istio.example
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer
    group: cert-manager.io
